package org.philblandford.ascore2.features.ui.model

enum class LayoutID {
  HOME, INSERT_CHOOSE, INSERT, KEYBOARD, PERCUSSION, EDIT_EVENT,
  LAYOUT, TRANSFORM, INSTRUMENT, CLEF, KEY, TIME, BAR, INSTRUMENT_INSERT,
  TEXT, LYRIC, HARMONY, TEMPO, SLUR, TIE,
  TUPLET,
  ORNAMENT, TREMOLO, ARTICULATION, BOWING, GLISSANDO, PAUSE, NAVIGATION, VOLTA,
  BARLINE, REPEAT_BAR, FINGERING, STAVE_LABEL, DYNAMIC, WEDGE, OCTAVE, PEDAL, PAGE_SIZE, SYSTEM_GAP, STAVE_GAP,
  SCORE_BREAK, SEGMENT_WIDTH,
  MARGIN,
  METADATA, LAYOUT_OPTIONS, GROUP_STAVES, BAR_NUMBERING,
  NEW_SCORE, NEW_SCORE_TEMPLATE, NEW_SCORE_TEMPLATE2, QUICK_SCORE, LOAD_SCORE, SAVE_SCORE, PRINT_SCORE,
  SET_TEMPLATE, EXPORT_PDF, EXPORT_JPG, EXPORT_MXML, EXPORT_MIDI, EXPORT_MP3, EXPORT_WAV, EXPORT_SAVE, IMPORT,
  SETTINGS_AUDIO, SETTINGS_LAYOUT, MANAGE_SOUNDFONT, PROGRESS, STARTUP, PLAYBACK, PLAYBACK_OPTIONS, MIXER,
  TRANSPOSE_TO, TRANSPOSE_BY, KEYBOARD_ONLY,

  INSTRUMENT_MENU, INSTRUMENT_EDIT,

  EDIT_CLEF, EDIT_KEY, EDIT_TIME, EDIT_TEMPO, EDIT_META, EDIT_TEXT, EDIT_LYRIC, EDIT_DYNAMIC, EDIT_CHORD, EDIT_OCTAVE,
  EDIT_WEDGE,

  EYE,

  PREFERENCES,
  PURCHASE,
  MANUAL,
  ABOUT,
  DONATE,

  EMPTY
}